### ISSUE TITLE
Any way to disable the creation of the ide-twig.json file?

### ISSUE THREAD

**Issue by pkamps** [netgen/site-bundle#41]
We're using cloud dev environments (not locally). We do not need the system to create the `ide-twig.json` file.
Is there an option to prevent the system of creating that file? We often run into file permission issues with that particular file.

https://github.com/netgen/site-bundle/blob/master/bundle/DependencyInjection/Compiler/PHPStormPass.php#L23

The dev environments have 'kernel.debug' === true.

**Comment by emodric** [comment]
I suppose we can add a parameter which defaults to `kernel.debug`, instead using `kernel.debug` directly. This would then be overriden in project code.

Would this work for you?

**Comment by pkamps** [comment]
That works - I like it.

**Comment by emodric** [comment]
@pkamps Released in `3.1.6`.

Set `ngsite.phpstorm_twig_integration.enabled: false` in your config to disable the pass.
