### ISSUE TITLE
Download Controller fails when attempting to download image

### ISSUE THREAD

**Issue by dfritschy** [netgen/site-bundle#52]
Download Controller fails on line https://github.com/netgen/site-bundle/blob/61bdf0bea044ddcf15272902a067971d4abd561f/bundle/Controller/Download.php#L66 with message

       Property 'mimeType' not found on class 'Ibexa\Core\FieldType\Image\Value'

as this property is named `$mime` in https://github.com/ibexa/core/blob/d6b1921454ec7d8bc73e304333922f93ac67b0b6/src/lib/FieldType/Image/Value.php#L97

This is a nasty difference to binary files https://github.com/ibexa/core/blob/d6b1921454ec7d8bc73e304333922f93ac67b0b6/src/lib/FieldType/BinaryBase/Value.php#L55 where this property is called `$mimeType`.

**Comment by emodric** [comment]
Thanks @dfritschy for the report, fixed in [3.2.3](https://github.com/netgen/site-bundle/releases/tag/3.2.3).
